# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./project-ml-microservice-kubernetes/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            cd project-ml-microservice-kubernetes
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./project-ml-microservice-kubernetes/venv
          key: v1-dependencies-{{ checksum "./project-ml-microservice-kubernetes/requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            cd project-ml-microservice-kubernetes
            . venv/bin/activate
            make lint

  build-docker-image:
    machine: true
    steps:
      - checkout
      - run:
        name: log in to docker io
        command: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
        name: build docker image
        command: |
          cd project-ml-microservice-kubernetes
          docker build . -t hungtruongquoc/udacity-devops:$CIRCLE_BRANCH

workflows:
  default:
    jobs:
      - build
      - build-docker-image
